---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  yaml: ./tasks/yaml.yml
  python: ./tasks/python.yml
  node: ./tasks/node.yml

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  run:
    desc: Run the project
    silent: true
    cmds:
      - task node:build
      - task python:run

  debug:
    desc: Run the project in debug mode
    silent: true
    cmds:
      - task node:build
      - task python:debug

  test:
    desc: Test the project
    silent: true
    cmds:
      - task python:test

  check:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - yaml:check
      - python:check
      - node:check
    cmds: []

  fix:
    desc: Fix linting/formatting errors
    silent: true
    deps:
      - yaml:fix
      - python:fix
    cmds: []
